### ISSUE TITLE
Getting the multer error

### ISSUE THREAD

**Issue by Umashankarsaw** [walkerblackwell/formio-upload-unauthenticated#6]
`MulterError: Unexpected field
    at wrappedFileFilter (D:\wfh\test\formio-upload-unauthenticated\node_modules\multer\index.js:40:19)
    at Busboy.<anonymous> (D:\wfh\test\formio-upload-unauthenticated\node_modules\multer\lib\make-middleware.js:114:7)
    at Busboy.emit (events.js:315:20)
    at Busboy.emit (D:\wfh\test\formio-upload-unauthenticated\node_modules\busboy\lib\main.js:38:33)
    at PartStream.<anonymous> (D:\wfh\test\formio-upload-unauthenticated\node_modules\busboy\lib\types\multipart.js:213:13)
    at PartStream.emit (events.js:315:20)
    at HeaderParser.<anonymous> (D:\wfh\test\formio-upload-unauthenticated\node_modules\dicer\lib\Dicer.js:51:16)
    at HeaderParser.emit (events.js:315:20)
    at HeaderParser._finish (D:\wfh\test\formio-upload-unauthenticated\node_modules\dicer\lib\HeaderParser.js:68:8)
    at SBMH.<anonymous> (D:\wfh\test\formio-upload-unauthenticated\node_modules\dicer\lib\HeaderParser.js:40:12)`

**Comment by walkerblackwell** [comment]
do you get this when you attempt to node index or when you attempt to upload?
